#!/bin/bash -xe
# -----------------------------------------------------------------------------
#  This script will bootstrap and baseline a Salt Master node, the heart of
#  the salt-openstack automation.   It can be specified as userdata script when
#  launching an OpenStack instance, or uploaded to and run on a baremetal node.
# -----------------------------------------------------------------------------
export PATH=/usr/sbin:/usr/bin:/sbin:/bin

# Upgrade the base system, install curl, git, and gnupg2 (for apt-key).
export DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical
apt-get update && apt-get dist-upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" 
apt-get install --no-install-recommends -y curl git gnupg2 jq lsb-release make openssh-client patch python3-yaml unzip

DEBIAN_MAJOR_VERSION=`awk -F '.' '{print $1}' /etc/debian_version`
DEBIAN_RELEASE_NAME=`lsb_release -sc`
DEFAULT_MINION_NAME=${DEFAULT_MINION_NAME:="$( hostname -s )"}

# Clone the upstream repository locally, setup symlinks, generate credentials.
rm -rfv /srv

if [ ! -z "${SALT_OPENSTACK_REPO}" ]; then
	mkdir /srv
	ln -sfv "${SALT_OPENSTACK_REPO}/pillar" /srv/pillar
	ln -sfv "${SALT_OPENSTACK_REPO}/salt" /srv/salt
	ln -sfv "${SALT_OPENSTACK_REPO}/scripts" /srv/scripts
	rm -fv "${SALT_OPENSTACK_REPO}/pillar/consul/bootstrap.sls"
else
	git clone https://github.com/tj90241/salt-openstack.git /srv
fi

# Download Consul, extract it into /usr/local/bin.
CONSUL_URL=`/usr/bin/env python3 -c "import yaml ; print(yaml.safe_load(open('/srv/pillar/consul/init.sls', 'r'))['consul']['package']['$( uname -m )']['source'])"`

CONSUL_TMP=`mktemp -d`
curl -s "${CONSUL_URL}" -o "${CONSUL_TMP}/$(basename ${CONSUL_URL})"
unzip -o "${CONSUL_TMP}/$(basename ${CONSUL_URL})" consul -d /usr/local/bin
rm -rfv "${CONSUL_TMP}"

# Generate credentials unless requested not to.
if [ -z "${USE_EXISTING_CREDENTIALS}" ]; then
	/srv/scripts/generate-credentials
fi

# Provision the upstream Saltstack repository.
SALT_VERSION=`/usr/bin/env python3 -c "import yaml ; print(yaml.safe_load(open('/srv/pillar/salt/init.sls', 'r'))['salt']['release'])"`
curl -sL "https://repo.saltstack.com/py3/debian/${DEBIAN_MAJOR_VERSION}/amd64/archive/${SALT_VERSION}/SALTSTACK-GPG-KEY.pub" | apt-key add -
echo "deb http://repo.saltstack.com/py3/debian/${DEBIAN_MAJOR_VERSION}/amd64/archive/${SALT_VERSION} ${DEBIAN_RELEASE_NAME} main" > /etc/apt/sources.list.d/saltstack.list
apt-get update

# Install and configure the local minion.
apt-get install -y salt-minion
echo "${DEFAULT_MINION_NAME}" > /etc/salt/minion_id
#echo 'grains: {roles: [salt-master]}' > /etc/salt/minion.d/grains.conf
echo 'master: 127.0.0.1' > /etc/salt/minion.d/master.conf
cat <<- EOF > /etc/salt/minion.d/superseded.conf 
use_superseded:
  - module.run
EOF

systemctl restart salt-minion

# Install the master.
apt-get install -y salt-master

# Ensure we only accept a key from the local minion for now.
# Poll until the local minion accepts to perform a key-exchange.
/usr/sbin/ifdown -a
/usr/sbin/ifup lo
salt-key -Dy
systemctl restart salt-minion

while [ 1 ]; do
  salt-key -a salt -y || /bin/true
  salt-key --no-color -l acc | grep "^${DEFAULT_MINION_NAME}\$" && break
done

# Wait for key acceptance, sync the world.
while [ 1 ]; do
  salt-call test.ping && break
  sleep 10
done

salt-run saltutil.sync_all
salt-call saltutil.sync_all

# No need to be lights-out anymore...
/usr/sbin/ifup -a
/usr/sbin/ifup --allow hotplug -a

# Baseline the master, poll till its up.  We do two provisioning passes
# because in case the master has a roles with recursive definitions.
for pass in first second; do
  salt-call state.apply salt.master

  while [ 1 ]; do
    salt-call test.ping && break
  done
done

# Baseline the minion, poll till its up.  We do two provisioning passes
# because in case the minion has a roles with recursive definitions.
for pass in first second; do
  salt-call state.apply salt.minion
  systemctl restart salt-minion

  while [ 1 ]; do
    salt-call test.ping && break
  done
done

# Wait for the Consul servers to become available, accept their keys.
CONSUL_SERVERS=`salt-call --output json pillar.get consul:site:server_fqdns | jq -r '.local | join(",")'`

while [ 1 ]; do
  salt -N consul-servers test.ping && break
  salt-key -a "${CONSUL_SERVERS}" -y || sleep 10
done

sleep 60

# Bootstrap the Consul cluster and highstate the nodes.
make -C /salt-openstack bootstrap-consul

salt-call state.apply certbot
salt-call state.apply certbot.renew
salt -C 'N@salt-masters or N@consul-servers' state.highstate
