#!/bin/bash -xe
# -----------------------------------------------------------------------------
#  This script will bootstrap and baseline a Salt Master node, the heart of
#  the salt-openstack automation.   It can be specified as userdata script when
#  launching an OpenStack instance, or uploaded to and run on a baremetal node.
# -----------------------------------------------------------------------------
DEBIAN_MAJOR_VERSION=`awk -F '.' '{print $1}' /etc/debian_version`
DEFAULT_MINION_NAME=${DEFAULT_MINION_NAME:="$( hostname -s )"}
export PATH=/usr/sbin:/usr/bin:/sbin:/bin

# Upgrade the base system, install curl, git, and gnupg2 (for apt-key).
export DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical
apt-get update && apt-get dist-upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" 
apt-get install -y curl git gnupg2 lsb-release openssh-client python3-yaml unzip

# Clone the upstream repository locally, setup symlinks, generate credentials.
rm -rfv /srv

if [ ! -z "${SALT_OPENSTACK_REPO}" ]; then
	mkdir /srv
	ln -sfv "${SALT_OPENSTACK_REPO}/pillar" /srv/pillar
	ln -sfv "${SALT_OPENSTACK_REPO}/salt" /srv/salt
else
	git clone https://github.com/tj90241/salt-openstack.git /srv
fi

# Download Consul, extract it into /usr/local/bin.
CONSUL_URL=`/usr/bin/env python3 -c "import yaml ; print(yaml.safe_load(open('/srv/pillar/consul/init.sls', 'r'))['consul']['package']['$( uname -m )']['source'])"`

CONSUL_TMP=`mktemp -d`
curl -s "${CONSUL_URL}" -o "${CONSUL_TMP}/$(basename ${CONSUL_URL})"
unzip -o "${CONSUL_TMP}/$(basename ${CONSUL_URL})" consul -d /usr/local/bin
rm -rfv "${CONSUL_TMP}"

exit 0

# Generate credentials if an existing repo was not provided.
if [ -z "${SALT_OPENSTACK_REPO}" ]; then
	/srv/scripts/generate-credentials
fi

# Provision the upstream Saltstack repository.
SALT_VERSION=`/usr/bin/env python3 -c "import yaml ; print(yaml.safe_load(open('/srv/pillar/salt/init.sls', 'r'))['salt']['release'])"`
curl -s "https://repo.saltstack.com/py3/debian/${DEBIAN_MAJOR_VERSION}/amd64/archive/${SALT_VERSION}/SALTSTACK-GPG-KEY.pub" | apt-key add -
echo "deb http://repo.saltstack.com/py3/debian/${DEBIAN_MAJOR_VERSION}/amd64/archive/${SALT_VERSION} $( lsb_release -sc ) main" > /etc/apt/sources.list.d/saltstack.list
apt-get update

# Don't block startup of services on systemd-wait-time-sync.
# It may not be provisioned yet.
mkdir -p /run/systemd/timesync
touch /run/systemd/timesync/synchronized > /dev/null 2>&1

# Install and configure the local minion.
apt-get install -y salt-minion
echo "${DEFAULT_MINION_NAME}" > /etc/salt/minion_id
echo 'grains: {roles: [salt-master]}' > /etc/salt/minion.d/grains.conf
echo 'master: localhost' > /etc/salt/minion.d/master.conf
cat <<- EOF > /etc/salt/minion.d/superseded.conf 
use_superseded:
  - module.run
EOF

systemctl restart salt-minion

# Install the master.
apt-get install -y salt-master

# Ensure we only accept a key from the local minion for now.
# Poll until the local minion accepts to perform a key-exchange.
/usr/sbin/ifdown -a
/usr/sbin/ifup lo
salt-key -Dy
systemctl restart salt-minion

while [ 1 ]; do
  salt-key -a salt -y || /bin/true
  salt-key --no-color -l acc | grep "^${DEFAULT_MINION_NAME}\$" && break
done

# Wait for key acceptance, sync the world.
while [ 1 ]; do
  salt-call test.ping && break
done

salt-run saltutil.sync_all
salt-call saltutil.sync_all

# No need to be lights-out anymore...
/usr/sbin/ifup -a
/usr/sbin/ifup --allow hotplug -a

# Baseline the master, poll till its up.
salt-call state.apply patch
salt-call state.apply salt.master

while [ 1 ]; do
  salt-call test.ping && break
done

# Baseline the minion, poll till its up.  We do two provisioning passes
# because in case the minion has a roles with recursive definitions.
for pass in first second; do
  salt-call state.apply salt.minion
  systemctl restart salt-minion

  while [ 1 ]; do
    salt-call test.ping && break
  done
done

# Run a highstate.
salt-call certbot
salt-call certbot.renew
salt-call consul.ca
salt-call state.highstate

# Reboot into a clean state.
systemctl reboot
