#!/bin/bash -xe
# -----------------------------------------------------------------------------
#  This script will bootstrap and baseline a Salt Master node, the heart of
#  the salt-openstack automation.   It can be specified as userdata script when
#  launching an OpenStack instance, or uploaded to and run on a baremetal node.
# -----------------------------------------------------------------------------
DEBIAN_MAJOR_VERSION=`awk -F '.' '{print $1}' /etc/debian_version`
DEFAULT_MINION_NAME=${DEFAULT_MINION_NAME:="$( hostname -s )"}

# Upgrade the base system, install curl, git, and gnupg2 (for apt-key).
export DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical
apt-get update && apt-get dist-upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" 
apt-get install -y curl git gnupg2

# Clone the upstream repository locally, setup symlinks, generate credentials.
rm -rfv /srv

if [ ! -z "${SALT_OPENSTACK_REPO}" ]; then
	mkdir /srv
	ln -sfv "${SALT_OPENSTACK_REPO}/pillar" /srv/pillar
	ln -sfv "${SALT_OPENSTACK_REPO}/salt" /srv/salt
else
	git clone https://github.com/tj90241/salt-openstack.git /srv
	/srv/scripts/generate-credentials
fi

# Provision the upstream Saltstack repository.
curl -s "https://repo.saltstack.com/py3/debian/${DEBIAN_MAJOR_VERSION}/amd64/archive/3002.2/SALTSTACK-GPG-KEY.pub" | apt-key add -
echo "deb http://repo.saltstack.com/py3/debian/${DEBIAN_MAJOR_VERSION}/amd64/archive/3002.2 buster main" > /etc/apt/sources.list.d/saltstack.list
apt-get update

# Don't block startup of services on systemd-wait-time-sync.
# It may not be provisioned yet.
mkdir -p /run/systemd/timesync
touch /run/systemd/timesync/synchronized > /dev/null 2>&1

# Install and configure the local minion.
apt-get install -y salt-minion
echo "${DEFAULT_MINION_NAME}" > /etc/salt/minion_id
echo 'grains: {roles: [salt-master]}' > /etc/salt/minion.d/grains.conf
echo 'master: localhost' > /etc/salt/minion.d/master.conf
cat <<- EOF > /etc/salt/minion.d/superseded.conf 
use_superseded:
  - module.run
EOF

systemctl restart salt-minion

# Install the master.
apt-get install -y salt-master

# Ensure we only accept a key from the local minion for now.
# Poll until the local minion accepts to perform a key-exchange.
/usr/sbin/ifdown -a
/usr/sbin/ifup lo
salt-key -Dy
systemctl restart salt-minion

while [ 1 ]; do
  salt-key -a salt -y || /bin/true
  salt-key --no-color -l acc | grep "^${DEFAULT_MINION_NAME}\$" && break
done

# Wait for key acceptance, sync the world.
while [ 1 ]; do
  salt-call test.ping && break
done

salt-run saltutil.sync_all
salt-call saltutil.sync_all

# No need to be lights-out anymore...
/usr/sbin/ifup -a
/usr/sbin/ifup --allow hotplug -a

# Baseline the master, poll till its up.
salt-call state.apply salt.master

while [ 1 ]; do
  salt-call test.ping && break
done

# Baseline the minion, poll till its up.
salt-call state.apply salt.minion
systemctl restart salt-minion

while [ 1 ]; do
  salt-call test.ping && break
done

# Run a highstate.
salt-call certbot
salt-call certbot.renew
salt-call state.highstate

# Reboot into a clean state.
systemctl reboot
