#!/bin/bash -xe
# -----------------------------------------------------------------------------
#  This script will bootstrap and baseline a Salt Minion node.  It can be
#  specified as userdata script when launching an OpenStack instance, or
#  uploaded to and run on a baremetal node.
# -----------------------------------------------------------------------------
DEBIAN_MAJOR_VERSION=`awk -F '.' '{print $1}' /etc/debian_version`
DEFAULT_MASTER_HOSTNAME=${DEFAULT_MASTER_HOSTNAME:="salt.$( hostname -d )"}
DEFAULT_MINION_NAME=${DEFAULT_MINION_NAME:="$( hostname -s )"}

# Upgrade the base system, install curl, and gnupg2 (for apt-key).
export DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical
apt-get update && apt-get dist-upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" 
apt-get install -y curl gnupg2

# Provision the upstream Saltstack repository.
curl -s "https://repo.saltstack.com/py3/debian/${DEBIAN_MAJOR_VERSION}/amd64/archive/3002.2/SALTSTACK-GPG-KEY.pub" | apt-key add -
echo "deb http://repo.saltstack.com/py3/debian/${DEBIAN_MAJOR_VERSION}/amd64/archive/3002.2 buster main" > /etc/apt/sources.list.d/saltstack.list
apt-get update

# Install and configure the minion.
mkdir -p /etc/salt/minion.d
echo "${DEFAULT_MINION_NAME}" > /etc/salt/minion_id
echo "master: ${DEFAULT_MASTER_HOSTNAME}" > /etc/salt/minion.d/master.conf
cat <<- EOF > /etc/salt/minion.d/superseded.conf 
use_superseded:
  - module.run
EOF

apt-get install -y salt-minion
systemctl start salt-minion

# Don't block startup of services on systemd-wait-time-sync.
# It may not be provisioned yet.
mkdir -p /run/systemd/timesync
touch /run/systemd/timesync/synchronized > /dev/null 2>&1

# Wait for key acceptance, sync the world.
while [ 1 ]; do
  salt-call test.ping && break
done

salt-call saltutil.sync_all

# Baseline the minion, poll till its up.
salt-call state.apply salt.minion
systemctl restart salt-minion

while [ 1 ]; do
  salt-call test.ping && break
done

# Run a highstate.
salt-call state.highstate

# Reboot into a clean state.
systemctl reboot
