#!/bin/bash

# Consul
cat <<- PASSWORD_SENTINEL > /srv/pillar/consul/key.sls
consul:
  key: '`/usr/local/bin/consul keygen`'
PASSWORD_SENTINEL

# DevPI
cat <<- PASSWORD_SENTINEL > /srv/pillar/devpi/root.sls
devpi:
  users:
    root: 
      password: '$( </dev/urandom tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' | head -c 16 )'
PASSWORD_SENTINEL

cat <<- PASSWORD_SENTINEL > /srv/pillar/openstack/devpi/user.sls
devpi:
  users:
    openstack: 
      password: '$( </dev/urandom tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' | head -c 16 )'
PASSWORD_SENTINEL
