#!/bin/bash

cat <<- PASSWORD_SENTINEL > /srv/pillar/devpi/root.sls
devpi:
  users:
    root: 
      password: '$( </dev/urandom tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' | head -c 16 )'
PASSWORD_SENTINEL

cat <<- PASSWORD_SENTINEL > /srv/pillar/openstack/devpi/user.sls
devpi:
  users:
    openstack: 
      password: '$( </dev/urandom tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' | head -c 16 )'
PASSWORD_SENTINEL
