#!/bin/bash

# Consul
cat <<- PASSWORD_SENTINEL > /srv/pillar/consul/key.sls
consul:
  key: '`/usr/local/bin/consul keygen`'
PASSWORD_SENTINEL

# DevPI
cat <<- PASSWORD_SENTINEL > /srv/pillar/devpi/root.sls
devpi:
  users:
    root: 
      password: '$( </dev/urandom tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' | head -c 16 )'
PASSWORD_SENTINEL

cat <<- PASSWORD_SENTINEL > /srv/pillar/openstack/devpi/user.sls
devpi:
  users:
    openstack: 
      password: '$( </dev/urandom tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' | head -c 16 )'
PASSWORD_SENTINEL

# Jenkins
mkdir -p /srv/pillar/jenkins/credentials
touch /srv/pillar/jenkins/credentials/init.sls
KEYPAIR_DIR=$( mktemp -d )
ssh-keygen -qt ed25519 -N '' -f "${KEYPAIR_DIR}/jenkins"

cat <<- PASSWORD_SENTINEL > /srv/pillar/jenkins/credentials/controller.sls
jenkins:
  controller:
    jks:
      password: '$( </dev/urandom tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' | head -c 16 )'

    keypair:
      private: |
PASSWORD_SENTINEL

while read -r line;
do
   echo "        ${line}" >> /srv/pillar/jenkins/credentials/controller.sls;
done < "${KEYPAIR_DIR}/jenkins"

cat <<- PASSWORD_SENTINEL > /srv/pillar/jenkins/credentials/node.sls
jenkins:
  node:
    user:
      name: jenkins
      password: '$( </dev/urandom tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' | head -c 16 )'

  controller:
    keypair:
      public: |
PASSWORD_SENTINEL

while read -r line;
do
   echo "        ${line}" >> /srv/pillar/jenkins/credentials/node.sls;
done < "${KEYPAIR_DIR}/jenkins.pub"

rm -rfv "${KEYPAIR_DIR}"
